AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  CustomDomainName:
    Type: String
    Default: "api.example.com"
    Description: "The custom domain name for the API"

  CertificateArn:
    Type: String
    Description: "ARN of the ACM certificate for the custom domain"

  HostedZoneId:
    Type: String
    Description: "The ID of the Route 53 hosted zone for the domain"

Resources:

  ServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  MyTopic:
    Type: AWS::SNS::Topic

  MyQueue:
    Type: AWS::SQS::Queue

  MyQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MyQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "sns.amazonaws.com"
            Action: "SQS:SendMessage"
            Resource: !GetAtt MyQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref MyTopic

  MyQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt MyQueue.Arn
      Protocol: sqs
      TopicArn: !Ref MyTopic

  SNSPublishLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda/sns_handler.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          TOPIC_ARN: !Ref MyTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MyTopic.TopicName
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApi
            Path: /publish
            Method: POST

  SQSLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda/sqs_handler.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          GITHUB_TOKEN: "{{resolve:secretsmanager:GITHUB_TOKEN}}"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - SQSPollerPolicy:
            QueueName: !GetAtt MyQueue.QueueName
        - AmazonRDSFullAccess
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:CreateSecret
              - secretsmanager:PutSecretValue
              - cloudformation:ListStacks
              - cloudformation:DescribeStacks
              - cloudformation:Wait
            Resource: "*"
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MyQueue.Arn
            BatchSize: 10

  CleanupRDSLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda/cleanup_rds.lambda_handler
      Runtime: python3.11
      CodeUri: ./lambda
      Environment:
        Variables:
          RETENTION_PERIOD: "3"
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonRDSFullAccess
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: "*"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: "rate(1 hour)"
            Enabled: true

  MyCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref CustomDomainName
      CertificateArn: !Ref CertificateArn
      EndpointConfiguration:
        Types:
          - REGIONAL

  BasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref MyCustomDomain
      RestApiId: !Ref ServerlessApi
      Stage: Prod

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref CustomDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt MyCustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt MyCustomDomain.RegionalHostedZoneId

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/publish"

  SNSPublishLambda:
    Description: "ARN of the SNS Publish Lambda Function"
    Value: !GetAtt SNSPublishLambda.Arn

  SQSLambda:
    Description: "ARN of the SQS Consumer Lambda Function"
    Value: !GetAtt SQSLambda.Arn

  CleanupRDSLambda:
    Description: "ARN of the Cleanup RDS Lambda Function"
    Value: !GetAtt CleanupRDSLambda.Arn

  CustomDomainUrl:
    Description: "Custom domain URL for the API"
    Value: !Sub "https://${CustomDomainName}/publish"
