AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  ServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda/handler.lambda_handler
      Runtime: python3.11
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApi
            Path: /hello
            Method: GET

  MyTopic:
    Type: AWS::SNS::Topic

  MyQueue:
    Type: AWS::SQS::Queue

  MyQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref MyQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "sns.amazonaws.com"
            Action: "SQS:SendMessage"
            Resource: !GetAtt MyQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref MyTopic

  MyQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt MyQueue.Arn
      Protocol: sqs
      TopicArn: !Ref MyTopic

  SNSPublishLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda/sns_handler.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          TOPIC_ARN: !Ref MyTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MyTopic.TopicName
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApi
            Path: /publish
            Method: POST

  SQSLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda/sqs_handler.lambda_handler
      Runtime: python3.11
      Policies:
        - AWSLambdaBasicExecutionRole
        - SQSPollerPolicy:
            QueueName: !GetAtt MyQueue.QueueName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MyQueue.Arn
            BatchSize: 10

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/publish"

  SNSPublishLambda:
    Description: "ARN of the SNS Publish Lambda Function"
    Value: !GetAtt SNSPublishLambda.Arn

  HelloWorldFunction:
    Description: "ARN of the Hello World Lambda Function"
    Value: !GetAtt HelloWorldFunction.Arn

  SQSLambda:
    Description: "ARN of the SQS Consumer Lambda Function"
    Value: !GetAtt SQSLambda.Arn
